id: 0
field_strength: [1300,1300,1300,1300]
magnet_dimension:
  - [10,10,10]
  - [10,10,10]
  - [10,10,10]
  - [10,10,10]
magnet_pos:
  - [-11.213, 3.201, 0]
  - [-7.174, -10.586,0]
  - [7.537, -10.638, 0]
  - [11.709,3.021, 0]
magnet_pos_offsets:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
magnet_angle:
  - [0,0,180]
  - [0,0,0]
  - [0,90,0]
  - [90,0,0]
magnet_angle_offsets:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
sensor_pos:
  - [-22.4,7.25,0]
  - [-14,-19.5,0]
  - [14.3,-19.6,0]
  - [22.325,6.675,0]
sensor_pos_offsets:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
sensor_angle:
  - [0,0,90]
  - [0,0,90]
  - [0,0,90]
  - [0,0,90]
sensor_angle_offsets:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
calibration:
  optimize: ['field_strength','magnet_pos','sensor_angle']
  max_nfev: 2000
