calibration:
  max_nfev: 2000
  optimize: [field_strength, sensor_pos, sensor_angle]
field_strength:
- !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    UtBefM5TlEA=
id: 0
magnet_angle:
- [-90, 0, 0]
magnet_angle_offsets:
- [0, 0, 0]
magnet_dimension:
- [10, 10, 10]
magnet_pos:
- [0, 0, 0]
magnet_pos_offsets:
- [0, 0, 0]
sensor_angle:
- [0, 0, 90]
- [0, 0, 90]
- [0, 0, 90]
- [0, 0, 90]
sensor_angle_offsets:
- - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ewIo1qlsHLw=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      nK8sIqWeJ7w=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      2SnO+4EJrj8=
- - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      3Ac8oJ1V+zs=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      L6YVIiXE+zg=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      isPzz4jg978=
- - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      zKnatdwLczg=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      eunIm0NTl7I=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      A0JIKDFF1b8=
- - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      mBWhBZjRxCs=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      IMhAEz5feyc=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      vn6bsToa+D8=
sensor_pos:
- [-22.4, 7.25, 0]
- [-14, -19.5, 0]
- [14.3, -19.6, 0]
- [22.325, 6.675, 0]
sensor_pos_offsets:
- - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      oDij03CI2z8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      BY5c5b163L8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Pa0Vv638hL8=
- - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      oN4VHRsx7j8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      7wb0PYFW2z8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      nF9kEa+z2b8=
- - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      KKwrI1THwz8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      AEOqf5UAwj8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      dnMW1Ceqw78=
- - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      HT1ewzpsyb8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      SINRm00w1T8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      GOp3b4TWsb8=
