calibration:
  max_nfev: 2000
  optimize: [field_strength, sensor_angle, sensor_pos]
field_strength: [1300,1300,1300]
id: 0
magnet_angle:
- [0, -90, 0]
- [0, 90, 60]
- [0, 90, -60]
magnet_angle_offsets:
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
magnet_dimension:
- [10, 10, 10]
- [10, 10, 10]
- [10, 10, 10]
magnet_pos:
- [0,11,0]
- [9.526279442,-5.5,0]
- [-9.526279442,-5.5,0]
magnet_pos_offsets:
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0]
sensor_pos:
  - [0,22,0]
  - [-22,0,0]
  - [0,-22,0]
  - [22,0,0]
sensor_pos_offsets:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
sensor_angle:
  - [0,0,90]
  - [0,0,180]
  - [0,0,270]
  - [0,0,0]
sensor_angle_offsets:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
