id: 1
field_strength: [1300,1300,1300]
magnet_offsets:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
magnet_angles:
  - [1,0,0]
  - [0,-2,0]
  - [2,0,0]
sensor_offsets:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
sensor_angles:
  - [0,0,-2]
  - [0,0,-1]
  - [0,0,1]
  - [0,0,2]
