id: 1
field_strength: [1100,1300,1400]
magnet_offsets:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
magnet_angles:
  - [0,0,1]
  - [0,1,0]
  - [1,0,0]
sensor_offsets:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
sensor_angles:
  - [0,0,0.5]
  - [0,0,-1]
  - [0,0,0.3]
  - [0,0,0.1]
