id: 0
field_strength: [1300,1300,-1300]
magnet_offsets:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
magnet_angles:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
sensor_offsets:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
sensor_angles:
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
  - [0,0,0]
